<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325141245 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "logs" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, text TEXT NOT NULL, loglevel VARCHAR(20) NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tags JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F08FC65CD6A1527DA5D6E63E ON "logs" (loglevel, timestamp)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE "logs"');
    }
}
