# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # ====================== Basic registry ======================
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # ====================== Services ======================

    # SinkFactory
    App\Factories\SinkFactory:
        arguments:
            $sinkConfig: '%unilogger.sinks%'

    # RequestSignatureValidator
    App\Security\RequestSignatureValidator:
        arguments:
            $secret: '%env(APP_SECRET)%'

    # Signature listener
    App\EventListener\RequestSignatureListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 100 }

    # Exception listener
    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -100 }

    # ====================== Sinks ======================
    unilogger.sink.database:
        class: App\Service\Sink\DatabaseSink
        tags: ['unilogger.sink']
